// Generated by https://quicktype.io

export interface UserResponse {
    user:    User;
    token:   string;
    message: string;
}

export interface User {
    favorites: string[];
    username:  string;
    email:     string;
    uid:       string;
}
